### PR TITLE
Input file fix

### LINKED ISSUE #122: `inputFiles` directory name is inconsistent
## Description
_Describe the bug here_
We changed the directory name in #106 but did not change it in other places
- inside the `get-input-files.sh` script
- in the various testing scripts that try to locate the input files

Since both of these were wrong, the script just extracted the files to a new directory called `inputFiles`, and nothing broke! This should be fixed though...

### PR DESCRIPTION
**Pull request by marcomangano**
## Purpose
Closes #122 . I uploaded on `mfile` a new `tar.gz` folder without subfolders, and changed the download bash script to untar directly into `input_files`. All the tests have been updated to point to this folder.

Note: the new `tar.gz` also includes a new `.cgns` file used for the rotating frame adjoint test added with #121 

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
The tests have been checked locally.

## Checklist

- [NA] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by nwu63 — DISMISSED** [review]

**Comment by nwu63** [comment]
@marcomangano did you also include the new cgns files for your rotation tests?

File: input_files/get-input-files.sh [hunk 1]
```diff
@@ -4,4 +4,4 @@
 
 DIR=$(dirname $0)
 wget -O $DIR/input_files.tar.gz http://umich.edu/~mdolaboratory/repo_files/ADflow/adflow_input_files.tar.gz
-tar -xzf $DIR/input_files.tar.gz -C $DIR/../
+tar -xzf $DIR/input_files.tar.gz -C $DIR
```
Comment (eirikurj) [inline input_files/get-input-files.sh:7]: Seems that the new file is a tarbomb. I personally think we should refrain from that types of behavior.

**Comment by marcomangano** [comment]
> @marcomangano did you also include the new cgns files for your rotation tests?

Yes!

File: input_files/get-input-files.sh (hunk 1 above)
Comment (marcomangano) [reply input_files/get-input-files.sh:7]: I thought it was safe because we were already opening it into a separate folder

Comment (nwu63) [reply input_files/get-input-files.sh:7]: I think Eirikur is in general against tarbombs which is fair, although in this case the script specifically extracts to a designated directory.

**Review by nwu63 — APPROVED** [review]
